### ISSUE TITLE
Change adrenaline to give 2adr on attack and 1 on hit

### ISSUE THREAD

**Issue by JOMO21** [JOMO21/GWRPGMaker#68]

**Comment by Hour-of-the-Owl** [comment]
I would argue that this is still probably too much adrenaline from getting hit. In GW you gain 1/25 for every 1% of your health you lose. To gain so much just from getting attacked you need to use a skill like Soldier's Defense. Having this as a passive effect seems OP, cheapening the value of attacking to gain adrenaline.
