### ISSUE TITLE
Change henchmen availability to be based on quest progress

### ISSUE THREAD

**Issue by JOMO21** [JOMO21/GWRPGMaker#76]
Nah was thinking 0 available immediately, talking to Lina and accepting quest makes one (let's say Alesia) show up and be a henchmen. And Stefan and Reyna can be unlocked via some other means, while Orion via the Wayward Wizard quest or custom followup.

**Comment by Hour-of-the-Owl** [comment]
How about having Little Thom instead of Stefan? After he gets his big cloak, he could be unlocked (at least until the Searing)

**Comment by Hour-of-the-Owl** [comment]
After the Searing, those unlock quests are presumably no longer available. What will happen to the henchmen you didn't unlock?

**Comment by JOMO21** [comment]
I like the idea of Little Thom. Can do that for sure. And correct. If there is ever post searing, then I guess any henchmen you don't recruit will be lost.
