### ISSUE TITLE
weapon comparison at the weaponsmith

### ISSUE THREAD

**Issue by Hour-of-the-Owl** [JOMO21/GWRPGMaker#81]
![image](https://user-images.githubusercontent.com/25005986/65880295-79808000-e389-11e9-8734-955384059d1c.png)
the bottom 2 stats are cut off, and there's no immediately apparent way to display them

**Comment by JOMO21** [comment]
https://forums.rpgmakerweb.com/index.php?threads/bm-mv-shop.62938/
See if this fixes issue
